title: Keynote
updated_by: a1054a8c-ce4f-42f3-98db-732d64f7c284
updated_at: 1647509704
blueprint: event_type
localizations:
  sk:
    title: Prednáška
    slug: keynote
    updated_by: a1054a8c-ce4f-42f3-98db-732d64f7c284
    updated_at: 1647509712
