title: 'Press conference'
updated_by: 5eadff7d-3e8d-45a4-9cd2-d732ae7834f2
updated_at: 1648058852
blueprint: event_type
localizations:
  sk:
    title: 'Tlačová beseda'
    slug: press-conference
    updated_by: 5eadff7d-3e8d-45a4-9cd2-d732ae7834f2
    updated_at: 1648060915
