title: 'Eugen Korda'
bio: 'Designer & creative director who works with people and brands that don''t shit on society and the environment.'
contact_email: hey@eugeneugen.eu
updated_by: a1054a8c-ce4f-42f3-98db-732d64f7c284
updated_at: 1647525722
blueprint: author
localizations:
  sk:
    bio: 'Designér a creative director, ktorý pracuje s ľuďmi a značkami that don''t shit on society and the environment.'
    slug: eugen-korda
    updated_by: a1054a8c-ce4f-42f3-98db-732d64f7c284
    updated_at: 1647525729
